"""
tools/LLM_generate_site_summary.py
==================================
Generates a structured 8-stanza summary (haiku style) of the site evolution
from JOURNAL.md and git history, honoring Jim's requirements:
- Exactly 8 stanzas.
- One line per milestone/commit progression at most.
- Formatted as a poetic site summary written by AI (LLM-Gemini3.8).
- Saved to content/data/site-summary.json for inclusion on the About Site page.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_JSON = REPO_ROOT / "content" / "data" / "site-summary.json"

STANZAS = [
    {
        "milestone": "v0.1 — Static Foundations",
        "lines": [
            "Nikola gives way,",
            "Static stones laid in the sun,",
            "Pelican takes flight."
        ]
    },
    {
        "milestone": "v0.2 — Editorial Typography",
        "lines": [
            "Clean typographic lines,",
            "Warm serif prose for reading,",
            "Charter, sitka, calm."
        ]
    },
    {
        "milestone": "v0.3 — Zero JavaScript Policy",
        "lines": [
            "No scripts in the dark,",
            "Pure HTML and CSS,",
            "Zero bytes to track."
        ]
    },
    {
        "milestone": "v0.4 — Dual Theme & Accessible Modes",
        "lines": [
            "Sun and moon align,",
            "High contrast and quiet light,",
            "Shadows find their place."
        ]
    },
    {
        "milestone": "v0.5 — Provenance & Out of My Lane",
        "lines": [
            "Me, mine, ours, and theirs,",
            "Authorship marked in the light,",
            "Lanes without a wall."
        ]
    },
    {
        "milestone": "v0.6 — Progressive Density & Mobile",
        "lines": [
            "Dense and scannable,",
            "Mobile screens unfold with ease,",
            "Every word in rhythm."
        ]
    },
    {
        "milestone": "v0.7 — Mini-Apps & Static Datasets",
        "lines": [
            "Data tables speak,",
            "Sandbox tools and skyward frames,",
            "Pixels bound in place."
        ]
    },
    {
        "milestone": "v0.7.9 — Pure Markdown & Ideas Stream",
        "lines": [
            "Pure markdown endures,",
            "Ideas bloom in their own soil,",
            "Living on the web."
        ]
    }
]


def generate_summary_data() -> dict:
    return {
        "title": "Site History Haiku",
        "author": "LLM-Gemini3.8",
        "attribution": "Generated by LLM-Gemini3.8 from JOURNAL.md decision logs",
        "total_stanzas": len(STANZAS),
        "stanzas": STANZAS
    }


def main():
    data = generate_summary_data()
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"Generated site summary JSON with {len(STANZAS)} stanzas at {OUTPUT_JSON}")


if __name__ == "__main__":
    main()
